// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmEHf8sYJ04-Q_niQoZpoSqsIZ80oKU98',
    appId: '1:331396298528:web:4016d214a8e57a1e150945',
    messagingSenderId: '331396298528',
    projectId: 'parking-system-fa249',
    authDomain: 'parking-system-fa249.firebaseapp.com',
    storageBucket: 'parking-system-fa249.appspot.com',
    measurementId: 'G-MQ804FZG4Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwuGixBFYwTjt3Op6cSsAytVDPno38D_k',
    appId: '1:331396298528:android:d47bc223f4e3ee9d150945',
    messagingSenderId: '331396298528',
    projectId: 'parking-system-fa249',
    storageBucket: 'parking-system-fa249.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBzavmmG-BMwPcFqlh2fYs-CuS86O1ruE',
    appId: '1:331396298528:ios:5ce5da8ca12a26c2150945',
    messagingSenderId: '331396298528',
    projectId: 'parking-system-fa249',
    storageBucket: 'parking-system-fa249.appspot.com',
    iosBundleId: 'co.devpaul.parkingSystem',
  );
}
